### ISSUE TITLE
BABA IS WATCHING

### ISSUE THREAD

**Issue by galvanized** [Aconka/babot#51]
hank, flag this with enhancement

- message statistics
  - messages per user
  - messages by month, day of week, hour of day
  - words frequently used by user

- markov generator (by user)

- voice use
  - sample users in voice channels periodically
  - sample voice activity?

will require database implementation

**Comment by Aconka** [comment]
not sure about this one:

voice use

    sample users in voice channels periodically
    sample voice activity?
